version: '3.8'

networks:
  laravel:

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
      - redis
      - mailhog
      - selenium
    networks:
      - laravel

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    build:
      context: ./.docker
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    build:
      context: ./.docker
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data
    networks:
      - laravel

  artisan:
    build:
      context: ./.docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "artisan"]
    networks:
      - laravel
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel

  selenium:
    image: 'seleniarm/standalone-chromium'
    ports:
      - 9515:9515
    volumes:
        - ./.docker/shm:/dev/shm
    networks:
        - laravel